name: solves-demo-app
services:
  - build_command: yarn build
    environment_slug: node-js
    github:
      branch: master
      deploy_on_push: true
      repo: pytkin/solves-demo-app
    name: solves-demo-app
